version: "3.9"

services:
  kafka-0:
    container_name: kafka-0
    hostname: kafka-0.insight.cl
    build: ./kafka
    image: insight/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - kafka-net

networks:
  kafka-net:
    name: kafka-net
    driver: bridge